### ISSUE TITLE
[uploadMultiple] Rails5.1 + Carrierwave multiple upload + this.options.uploadMultiple: true ( file[n] ---> file[])

### ISSUE THREAD

**Issue by charlietag** [ncuesta/dropzonejs-rails#45]
Can this be a config also like uploadMultipleAppend: [] , [n]
Because in rails it would be really useful to use only 

`<input id="member_picture" multiple="multiple" type="file" name="member[picture][]" />`

I now manually change source code here to solve multple upload in one request
From:

`return "" + this.options.paramName + (this.options.uploadMultiple ? "[" + n + "]" : ""); `

To:

`return "" + this.options.paramName + (this.options.uploadMultiple ? "[]" : ""); `

Thanks for your great efforts!

**Comment by ncuesta** [comment]
Hi @charlietag, I think you're requesting to have Dropzone's source code changed, but this gem is a simple wrapper around the JS library.

If that's right, you may want to send a PR on the [JS library repo](https://github.com/enyo/dropzone/).

Otherwise, I may have misunderstood you. If so, please feel free to reopen this issue and let the conversation flow :)

**Comment by charlietag** [comment]
Yes, you're right. Thank you.
